### ISSUE TITLE
inspect jenkins-slave image and minimize it's size as much as possible

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#27]
I already commented installation of some tooling but size of the alpine image is still around 1Gb which is pretty huge.
In scope of this research I'd like to get answers onto the below questions about toolset and sizing because original alpine image is about 6Mb only :)
```
alpine                                              3.11.3                         e7d92cdc71fe        9 months ago        5.59MB
```

1. What tools are installed by this command? their size and necessity for slave:
https://github.com/zebrunner/jenkins-slave/blob/83bc0d60e911c09f0f728b57d89d7f09c5f9cf64/Dockerfile#L15
2. size of docker components:
https://github.com/zebrunner/jenkins-slave/blob/83bc0d60e911c09f0f728b57d89d7f09c5f9cf64/Dockerfile#L39
3. Find commit and maybe person who requested to install kubectl, size of the image without it:
https://github.com/zebrunner/jenkins-slave/blob/83bc0d60e911c09f0f728b57d89d7f09c5f9cf64/Dockerfile#L45
4. size of the preinstalled 3.6.3 maven
https://github.com/zebrunner/jenkins-slave/blob/83bc0d60e911c09f0f728b57d89d7f09c5f9cf64/Dockerfile#L103
5. size of the java, inspect maybe other java version already installed...
https://github.com/zebrunner/jenkins-slave/blob/83bc0d60e911c09f0f728b57d89d7f09c5f9cf64/Dockerfile#L113

6. We already use M3 maven installed by jenkins from internet. So installing 3.6.3 maven again in the slave seems overhelming. But to main a decision we have to measure execution time for web-demo-test job as is and with removed maven&carina-demo dependencies. If time the same, please do 3 attempts with maven + carina-demo and without and collect statistic.

**Comment by vdelendik** [comment]
removed from general packages:
qt5-qtbase-dev
socat
gcc
musl-dev
gnupg

also removed kubectl, embedded 3.6.3 maven and carina dependencies.
As result size of the slave compressed in 2-3 times
```
REPOSITORY                                          TAG                            IMAGE ID            CREATED             SIZE
zebrunner/jenkins-slave                             1.1-jdk8-beta1                 14303a5f5a72        2 minutes ago       480MB
zebrunner/jenkins-slave                             1.1-beta1                      b75361269619        5 minutes ago       650MB
```

1.1-beta1 is declared in zebrunner (branch develop). To test 
1. setup and clone from develop branch
2. ensure that 1.1-beta1 is used and image size is 650MB
3. execute full_regression job

**Comment by okamara** [comment]
Verified.
