### ISSUE TITLE
install adb into the jenkins-slave

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#29]
try to integrate android adb tools into the jenkins slave without installing android sdk. better to integrate into the new slave generated from https://github.com/zebrunner/jenkins-slave/issues/28

**Comment by vdelendik** [comment]
https://github.com/zebrunner/jenkins-slave/commit/c885116780ae38817698a7a89dec0c1aa32cce8d
optimized set of tools for default executor slave decreasing image size in 2-3 times.
Also adb is installed w/o android sdk setup
```
RUN apk add \
    android-tools \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
``

**Comment by vdelendik** [comment]
test scenario:
```
docker exec -ti jenkins-salve bash
which adb
adb devices
```
above command could be executed successfully, no devices detected - that's expected

**Comment by okamara** [comment]
bash-5.0# adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
