### ISSUE TITLE
produce jenkins-slave with docker support

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#30]
we need jenkins-slave image where we can execute docker related tasks. As of now - no need to install maven, java etc...

**Comment by vdelendik** [comment]
appropriate slave generated and pushed:
zebrunner/jenkins-slave:1.1-docker

new Dockerfile-docker file is responsible for it

to test we have to 
1. reuse above 1.1-docker as a slave tag in jenkins/.env
2. after statr connect to slave `docker exec -ti jenkins-slave bash`
3. run successfully any docker command like
```
docker images
docker ps -a
```
-> no error message that docker program not exist or socket not available...

**Comment by dhreben** [comment]
Verified.
