### ISSUE TITLE
no java11 on docker slave image

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#33]
/entrypoint.sh: line 7: java: command not found

**Comment by vdelendik** [comment]
republished zebrunner/jenkins-slave:1.1-docker imgae.
so to test 
1. pull zebrunner from develop
2. uncomment in ./jenkins/docker-compose.yml slave for docker
3. start and connect to jenkins-slave-docker and run any docker command
```
docker exec -ti jenkins-slave-docker bash
docker ps -a
docker images
```
-> inside the container you should be able to see images and running containers on host

**Comment by okamara** [comment]
Done.
