### ISSUE TITLE
remove JENKINS_MASTER_PASSWORD var from entrypoint

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#42]
env var should be used but can't be delivered to jenkins master as env variable

**Comment by vdelendik** [comment]
fixed. testing might be done using zebrunner branch: develop.
to confirm that everything is good freestyle job should be created manually in jenkins with:
1. Restrict where this project can be run `maven`
2. Single build step `execute shell`
3.  Command `export`:
![image](https://user-images.githubusercontent.com/4551455/127343570-2872f281-8f17-4d10-9ad0-ed7ed36ca117.png)
![Uploading image.png…]()

after execution scan console log to make sure that there is no JENKINS_MASTER_PASSWORD value inside

**Comment by okamara** [comment]
Verified on dev. env and qa env. via https://ci.qaprosoft.farm/job/ZEB-3427/
