### ISSUE TITLE
install 31.0.2-android-tools package

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#44]
31.0-rc2 seems work correct with MCloud so we have to return this utility into the default jenkins slave

**Comment by vdelendik** [comment]
fixed. to test 
1. setup zebrunner CE from develop branch
2.  start everything
3. login into the jenkins-slave using bash: `docker exec -ti jenkins-slave bash`
4. verify that adb is preinstalled:
```
 adb --version
Android Debug Bridge version 1.0.41
Version 31.0.2-android-tools
Installed as /usr/bin/adb
```
5. Try to connect into any remote device from mCloud
-> device should be connected and listed among attached by `adb devices` command

**Comment by dhreben** [comment]
Verified.
