### ISSUE TITLE
add python slave

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#49]
let's build using `python:alpine3.14` docker image

**Comment by vdelendik** [comment]
done: `public.ecr.aws/zebrunner/jenkins-slave:1.5-python`
@okamara to test I can recommend:
1. stop everything
2. update `./jenkins/docker-compose.yml` replacing `...-docker` by `...-python` for secondary jenkins agent.
3. start everything
4. verify agent is connected and online
5. connect to the agent using `docker exec -ti jenkins-slave-docker bash`
Note: naming might be related to docker as we change only image addres
6. verify that pythin is installed using
```
which python
python --version
```

**Comment by okamara** [comment]
Verified, I got Python 3.7.12 version.
