### ISSUE TITLE
invetsigate possibility to name slaves using dynamic random appendix

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#50]
due to the crashes in swarm from time to time slave can't be re-registered. let's investigate possibility to provide random name posfix like:
jenkins-slave-python-PP86436734

**Comment by vdelendik** [comment]
to achieve it seems like we have to 
1. remove JENKINS_SLAVE_NAME from https://github.com/zebrunner/jenkins-slave/blob/f0faee47e95746cabcb4d9dede7c9f9cffb92762/variables.env.original#L3 and https://github.com/zebrunner/jenkins-master/blob/5f9e65b94ebf8520707b1d9350d946e7d49ed8ea/docker-compose.yml#LL26C20-L26C20
2. as result it should reuse random based on this logic: https://github.com/zebrunner/jenkins-slave/blob/f0faee47e95746cabcb4d9dede7c9f9cffb92762/Dockerfile#L65

sync with @vdelendik if approach works to define default delivery strategy

**Comment by azarouski** [comment]
PR https://github.com/zebrunner/jenkins-slave/pull/70

**Comment by azarouski** [comment]
arg `-disableClientsUniqueId` for run `swarm-client.jar` was removed

**Comment by okamara** [comment]
verified on develop branch, fixed.
<img width="873" alt="Снимок экрана 2023-06-26 в 17 19 45" src="https://github.com/zebrunner/jenkins-slave/assets/32964663/1efc4135-3c4f-4e88-b204-9ef5bfe45ba4">
