### ISSUE TITLE
provide alpine slave with docker on board

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#58]
let's provide alpine image with docker on-board already

**Comment by vdelendik** [comment]
done: public.ecr.aws/zebrunner/jenkins-slave:1.4-docker

**Comment by okamara** [comment]
Verified on CE in develop branch ->310bd0a5423e   public.ecr.aws/zebrunner/jenkins-slave:1.5-beta2
I didn't see -> public.ecr.aws/zebrunner/jenkins-slave:1.4-docker

**Comment by vdelendik** [comment]
@okamara by default it is not included/enabled in CE. 
image is available: public.ecr.aws/zebrunner/jenkins-slave:1.4-docker

also for upcoming v1.5 it is: public.ecr.aws/zebrunner/jenkins-slave:1.5-docker-beta2
Testing should include 
1. setup CE using develop branch
2. uncommenting docker agent from [jenkins/docker-compose.yaml](https://github.com/zebrunner/jenkins-master/blob/acf8517ef3b2662512e68ebcdf0ec4b25b19df9d/docker-compose.yml#L32)
3. restart of the services
-> jenkins agent with `docker` label is connected and online in jenkins
4. bash into the agent via `docker exec -ti jenkins-slave-docker bash`
5. list alailable containers `docker ps -a`
-> command should be executed successfully all started containers on host are visible.

**Comment by okamara** [comment]
Verified, fixed.
