### ISSUE TITLE
make jdk17 default one

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#60]
decomission jdk11 and produce by default with jdk17 on board. make sure jenkins master also uses jdk17 (?!)

**Comment by vdelendik** [comment]
Such new images built and published:
```
public.ecr.aws/zebrunner/jenkins-slave:1.5-beta2
public.ecr.aws/zebrunner/jenkins-slave:1.5-docker-beta2
public.ecr.aws/zebrunner/jenkins-slave:1.5-jnpl-beta2
public.ecr.aws/zebrunner/jenkins-slave:1.5-python-beta2
```

still TBD howto test all of them.

**Comment by okamara** [comment]
I could find only "public.ecr.aws/zebrunner/jenkins-slave    1.5-beta2"
<img width="884" alt="Снимок экрана 2023-03-22 в 12 28 52" src="https://user-images.githubusercontent.com/32964663/226859605-3f9a9b14-8ad0-41f4-b2b5-c7a7cc71dc3c.png">

**Comment by vdelendik** [comment]
full list of generated jenkins-agent images can be found in public listing (Image tags tab):
https://gallery.ecr.aws/zebrunner/jenkins-slave

**Comment by vdelendik** [comment]
verified on my own
