### ISSUE TITLE
investigate an option to make smarm-plugin dynamically compatible

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#64]
let's investigate an option to download sarm-plugin.jar from jenkins-master before start.
it should guarantee that our slaves can automatically reconnect to upgraded swarm on master.

make sure to validate the sate of the downloaded jar (via curl or wget?) and only if everything is ok - replace default one we provide with image.

**Comment by vdelendik** [comment]
based on my understanding we can improve entrypoint start script in such way:
1. before [the start](https://github.com/zebrunner/jenkins-slave/blob/f0faee47e95746cabcb4d9dede7c9f9cffb92762/entrypoint.sh#L23) download compatible swarm plugin from jenkins master using ${JENKINS_URL}/swarm/swarm-client.jar
Note: make sure to download with overriding file if any to support redownloading on restart
2. exit with `-1` failure if you couldn't to the jenkins master url
3. continue with the start steps using compatible jar file

if all good we can skip #67 and just remove jar files from image

**Comment by azarouski** [comment]
- swarm-client.jar was removed from image
- downloading swarm-client file was automated
need to test different scenarios and check stability of establishing connection between `Built-in` node and `Client` node

**Comment by okamara** [comment]
verified on develop branch.
<img width="1063" alt="Снимок экрана 2023-06-26 в 15 52 03" src="https://github.com/zebrunner/jenkins-slave/assets/32964663/6bbb5474-1429-45c1-88c6-f4c206fa22e2">
