### ISSUE TITLE
remove swarm jar binary from the repository

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#67]
it is not recommended to publish any binary files. let's improve Dockerfile uploading exact swarm plugin jar during docker image build.
for example take a look how the same exercise was done for sonarqube jar plugin: https://github.com/zebrunner/sonarqube/blob/f4db117c809250f5df2c7372a1f4b9c8a3fbe8ee/Dockerfile#L26

**Comment by azarouski** [comment]
`swarm-client.jar` was removed from docker image
